name: Hacktoberfest Labeler

on:
  pull_request:
    types:
      - closed

jobs:
  label-merged-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged
        id: check_merged
        run: echo "::set-output name=is_merged::$(if [[ ${GITHUB_EVENT_NAME} == 'pull_request' && ${GITHUB_EVENT_ACTION} == 'closed' && $(jq -r '.pull_request.merged' ${GITHUB_EVENT_PATH}) == 'true' ]]; then echo true; else echo false; fi)"

      - name: Add Hacktoberfest Label
        if: steps.check_merged.outputs.is_merged == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH")
          echo "Adding 'hacktoberfest-accepted' label to PR #$PR_NUMBER"
          curl -X POST "https://api.github.com/repos/${{ github.repository }}/pull/$PR_NUMBER/labels" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -d '["hacktoberfest-accepted"]'